spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=validate
server.port=8081

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT Configuration
jwt.secret=dGFza21hbmFnZXItc2VjcmV0LWtleS1mb3Itand0LWF1dGhlbnRpY2F0aW9uLTIwMjQ=
jwt.expiration=86400000